function MapFig = createMapFig(Rob,Sen,Lmk,Wrd,MapFigure)

% Figure
MapFig.fig = figure(1);
clf
set(MapFig.fig,...
    'doublebuffer','on',...
    'renderer',MapFigure.renderer,...
    'toolbar','none',...
    'color','w');
cameratoolbar('show');
cameratoolbar('setmode','orbit');

% Map viewpoint
viewPnt       = mapObserver(Wrd,MapFigure.view);

% Axes
axis equal
MapFig.axes = gca;
set(MapFig.axes,...
    'parent',MapFig.fig,...
    'position',[0 0 1 1],...
    'drawmode','fast',...
    'nextplot','replacechildren',...
    'projection',MapFigure.projection,...
	'CameraPosition',viewPnt.X,...
	'CameraPositionMode','manual',...
	'CameraUpVector',viewPnt.upvec,...
	'CameraUpVectorMode','manual',...
	'CameraViewAngle',viewPnt.fov,...
	'CameraViewAngleMode','manual',...
	'CameraTarget',viewPnt.tgt,...
	'CameraTargetMode','manual',...
    'xlim',[Wrd.xMin Wrd.xMax],...
    'ylim',[Wrd.yMin Wrd.yMax],...
    'zlim',[Wrd.zMin Wrd.zMax],...
    'xcolor','w',...
    'ycolor','w',...
    'zcolor','w',...
    'color' ,'w');

% Ground
[x,y] = meshgrid(Wrd.xMin:2:Wrd.xMax,Wrd.yMin:2:Wrd.yMax);
z = zeros(size(x));
MapFig.ground = surface(...
    'parent',MapFig.axes,...
    'XData',x,...
    'YData',y,...
    'ZData',z,...
    'FaceColor','none',...
    'EdgeColor',[.6 .8 .8],...
    'Marker','none');

% Robots
for rob = 1:numel(Rob)
    % Simulated - green
    MapFig.simRob(rob) = patch(...
        'parent',       MapFig.axes,...
        'vertices',     Rob(rob).graphics.vert,...
        'faces',        Rob(rob).graphics.faces,...
        'facecolor',    'g',...
        'visible',      'on');
    
    MapFig.simRob(rob) = drawObject(MapFig.simRob(rob),Rob(rob));
    
    % Estimated - blue
    MapFig.estRob(rob) = patch(...
        'parent',       MapFig.axes,...
        'vertices',     Rob(rob).graphics.vert,...
        'faces',        Rob(rob).graphics.faces,...
        'facecolor',    'b',...
        'visible',      'on');
    
    MapFig.estRob(rob) = drawObject(MapFig.estRob(rob),Rob(rob));
    
end

% Sensors
for sen = 1:numel(Sen)
    % Simulated - green
    MapFig.simSen(sen) = patch(...
        'parent',       MapFig.axes,...
        'vertices',     Sen(sen).graphics.vert,...
        'faces',        Sen(sen).graphics.faces,...
        'facecolor',    'g',...
        'visible',      'on');
    
    R = Rob(Sen(sen).robot);
    F = composeFrames(R.frame,Sen(sen).frame);
    MapFig.simSen(sen) = drawObject(MapFig.simSen(sen),Sen(sen),F);

    % Estimated - blue
    MapFig.estSen(sen) = patch(...
        'parent',       MapFig.axes,...
        'vertices',     Sen(sen).graphics.vert,...
        'faces',        Sen(sen).graphics.faces,...
        'facecolor',    'b',...
        'visible',      'on');
    
    R = Rob(Sen(sen).robot);
    F = composeFrames(R.frame,Sen(sen).frame);
    MapFig.estSen(sen) = drawObject(MapFig.estSen(sen),Sen(sen),F);

end

