function Con = createControls(Robot)

% CREATECONTROLS  Create controls structure Con.
%   Con = CREATECONTROLS(ROBOT) generates an array of control structures
%   Con, the same size of ROBOTS. This structure depends on the motion
%   models of each robot, and contains the fields:
%       .u      nominal value of control
%       .uStd   Standard deviation of control noise
%       .U      Covariances matrix
%
%   The resulting structure need to be updated during execution time with
%   data from one of these origins: 
%       1. read from odometry sensors
%       2. generated by a control software
%       3. generated by the simulator.
%
%   See also CREATEROBOTS.

for rob = 1:numel(Robot)
    
    Con(rob).robot = Robot{rob}.id;
    
    switch Robot{rob}.motion
        
        case {'constVel'}
            
            Con(rob).u    = [Robot{rob}.dv;deg2rad(Robot{rob}.dwDegrees)];
            Con(rob).uStd = [Robot{rob}.dvStd;deg2rad(Robot{rob}.dwStd)];
            Con(rob).U    = diag(Con(rob).uStd.^2);
                        
        case {'odometry'}
            
            Con(rob).u    = [Robot{rob}.dx;deg2rad(Robot{rob}.daDegrees)];
            Con(rob).uStd = [Robot{rob}.dxStd;deg2rad(Robot{rob}.daStd)];
            Con(rob).U    = diag(Con(rob).uStd.^2);
                        
        otherwise
            error('Unknown motion model %s from robot %d.',Robot{rob}.motion,Robot{rob}.id);
    end
end
