function drawIdpLmk(MapFig, Lmk, color)
global Map

posOffset = [0;0;.05];

ran=Lmk.state.r;

% the ellipse
[X,Y,Z] = idp3elli(Map.x(ran), Map.P(ran,ran), 3, 10) ;
set(MapFig.estLmk(Lmk.lmk).ellipse,...
    'xdata',   X,...
    'ydata',   Y,...
    'zdata',   Z,...
    'color',   color,...
    'visible', 'on');

% the measurement:
y = idp2p(Map.x(ran));
set(MapFig.estLmk(Lmk.lmk).mean,...
    'xdata',   y(1),...
    'ydata',   y(2),...
    'zdata',   y(3),...
    'color',   color,...
    'visible', 'on');

% the label
set(MapFig.estLmk(Lmk.lmk).label,...
    'position', y + posOffset,...
    'string',   num2str(Lmk.id),...
    'visible',  'on');
