function drawIdpLmk(MapFig, Lmk, color)
global Map
ran=Lmk.state.r;




[X,Y,Z] = idp3elli(Map.x(ran), Map.P(ran,ran), 3, 10) ;
set(MapFig.estLmk(lmk).ellipse,...
    'xdata', X,...
    'ydata', Y,...
    'zdata', Z,...
    'color', color,...
    'visible',   'on');