% INITDRAWMAPLMKS  Initialize graphics for map landmarks

% rays
for i=1:Ng*Lmk.maxRay
    dispMapRay.elli(i) = line(...
        'parent',ax1,...
        'xdata',[],...
        'ydata',[],...
        'color',[1 .7 .7],...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1);
end

dispMapRay.center = line(...
    'parent',ax1,...
    'xdata',[],...
    'ydata',[],...
    'color','r',...
    'marker','.',...
    'linestyle','none');

% points
for i=1:Lmk.maxPnt
    dispMapPnt.elli(i) = line(...
        'parent',ax1,...
        'xdata',[],...
        'ydata',[],...
        'color',[.7 .7 1],...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1);
end

dispMapPnt.center = line(...
    'parent',ax1,...
    'xdata',[],...
    'ydata',[],...
    'color','b',...
    'marker','.',...
    'linestyle','none');


