function handle = createSimLmkGraphics(SimLmk,colr,ax)

% CREATESIMLMKGRAPHICS  Crate simulated landmark graphics.
%   CREATESIMLMKGRAPHICS(SIMLMK,LBLCLR) creates the graphics objects for the
%   simulated landmarks SIMLMK.
%
%   CREATESIMLMKGRAPHICS(...,AX) creates the graphics at axes AX.
%
%   HSTR = CREATESIMLMKGRAPHICS returns a handle to the 'line' graphics object.

if nargin < 3
    ax = gca;
end

handle = line(...
    'parent',       ax,...
    'xdata',        SimLmk.points.coord(1,:),...
    'ydata',        SimLmk.points.coord(2,:),...
    'zdata',        SimLmk.points.coord(3,:),...
    'color',        colr,...
    'linestyle',    'none',...
    'marker',       '+');
