function handleStr = createLmkGraphics(Lmk,labelColor,ax)

%CREATELMKGRAPHICS Create landmark graphics.
%   CREATELMKGRAPHICS(LMK,LBLCLR) creates the graphics objects for the
%   landmark LMK: a 3-sigma ellipsoid, a mean point, and a label with color
%   LBLCLR.
%
%   CREATELMKGRAPHICS(...,AX) creates the graphics at axes AX.
%
%   HSTR = CREATELMKGRAPHICS returns a structure of handles for the three
%   objects plus a flag for drawn landmarks:
%       HSTR.drawn      is landmark drawn?
%       HSTR.mean       the mean
%       HSTR.ellipse()  the 3-sigma ellipsoids
%       HSTR.label      the label.

%   Copyright 2008-2009 Joan Sola @ LAAS-CNRS.

if nargin < 3
    ax = gca;
end

handleStr.drawn = false;     % flag for drawn landmark

handleStr.mean = line(...    % for the means, point or segment
    'parent',       ax,...
    'xdata',        [],...
    'ydata',        [],...
    'zdata',        [],...
    'linestyle',    '-',...
    'linewidth',    2,...
    'marker',       '.',...
    'visible',      'off');

handleStr.ellipse(1) = line(...  % for covariances, point or segment
    'parent',       ax,...
    'xdata',        [],...
    'ydata',        [],...
    'zdata',        [],...
    'linestyle',    '-',...
    'marker',       'none',...
    'visible',      'off');

handleStr.ellipse(2) = line(... % for covariances, only for segments
    'parent',       ax,...
    'xdata',        [],...
    'ydata',        [],...
    'zdata',        [],...
    'linestyle',    '-',...
    'marker',       'none',...
    'visible',      'off');

handleStr.label = text(...    % for the label, point or segment
    'parent',              ax,...
    'string',              num2str(Lmk.lmk),...
    'color',               labelColor,...
    'fontsize',            10,...
    'fontweight',          'normal',...
    'horizontalalignment', 'center',...
    'visible',             'off');










