function handle = createGround(SimLmk,ax)

if nargin < 2
    ax = gca;
end

[x,y] = meshgrid(SimLmk.lims.xMin:2:SimLmk.lims.xMax,SimLmk.lims.yMin:2:SimLmk.lims.yMax);
z = zeros(size(x));
handle = surface(...
    'parent',     ax,...
    'XData',      x,...
    'YData',      y,...
    'ZData',      z,...
    'FaceColor',  'none',...
    'EdgeColor',  [.6 .8 .8],...
    'Marker',     'none');
