function handle = createSimLmkGraphics(SimLmk,colr,ax)

% CREATELMKGRAPHICS  Crate simulated landmark graphics.
%   CREATELMKGRAPHICS(SIMLMK,LBLCLR) creates the graphics objects for the
%   simulated landmarks SIMLMK.
%
%   CREATELMKGRAPHICS(...,AX) creates the graphics at axes AX.
%
%   HSTR = CREATELMKGRAPHICS returns a handle to the 'line' graphics object.

if nargin < 3
    ax = gca;
end

handle = line(...
    'parent',       ax,...
    'xdata',        SimLmk.points(1,:),...
    'ydata',        SimLmk.points(2,:),...
    'zdata',        SimLmk.points(3,:),...
    'color',        colr,...
    'linestyle',    'none',...
    'marker',       '+');
