function drawGauss2dPnt(hnds,x,P,label,color,posOffset,ns,NP)

% DRAWGAUSS3DPNT  Draw Gaussian 2d point.

if nargin < 8
    NP = 10;
    if nargin < 7
        ns = 3;
    end
end

% the expectation's mean:
if isfield(hnds,'mean') && ishandle(hnds.mean) && hnds.mean
    set(hnds.mean,...
        'xdata',   x(1),...
        'ydata',   x(2),...
        'color',   color,...
        'visible', 'on');
end

% the expectation's ellipse
[X,Y] = cov2elli(x, P, ns, NP) ;
set(hnds.ellipse,...
    'xdata',   X,...
    'ydata',   Y,...
    'color',   color,...
    'visible', 'on');

% the label
set(hnds.label,...
    'position', x + posOffset,...
    'string',   label,...
    'visible',  'on');
