function drawEucPnt(MapFig, Lmk, color)

% DRAWEUCPNT  Draw Euclidean point landmark in MapFig.

global Map

posOffset = [0;0;.2];

% Mean and covariance
x = Map.x( Lmk.state.r);
P = Map.P(Lmk.state.r,Lmk.state.r);

% the expectation's mean:
set(MapFig.Lmk(Lmk.lmk).mean,...
    'xdata',   x(1),...
    'ydata',   x(2),...
    'zdata',   x(3),...
    'color',   satColor(color),...
    'visible', 'on');

% the expectation's ellipse
[X,Y,Z] = cov3elli(x, P, 3, 10) ;
set(MapFig.Lmk(Lmk.lmk).ellipse,...
    'xdata',   X,...
    'ydata',   Y,...
    'zdata',   Z,...
    'color',   color,...
    'visible', 'on');

% the label
set(MapFig.Lmk(Lmk.lmk).label,...
    'position', x + posOffset,...
    'string',   num2str(Lmk.id),...
    'visible',  'on');