function drawPnt(pntHandles,x,P,color)

% DRAWPNT  Draw 3D Gaussian point with covariance and label.

posOffset = [0;0;.2];

% the expectation's mean:
set(pntHandles.mean,...
    'xdata',   x(1),...
    'ydata',   x(2),...
    'zdata',   x(3),...
    'color',   satColor(color),...
    'visible', 'on');

% the expectation's ellipse
[X,Y,Z] = cov3elli(x, P, 3, 10) ;
set(pntHandles.ellipse,...
    'xdata',   X,...
    'ydata',   Y,...
    'zdata',   Z,...
    'color',   color,...
    'visible', 'on');

% the label
set(pntHandles.label,...
    'position', x + posOffset,...
    'string',   num2str(Lmk.id),...
    'visible',  'on');
