function wstruct = swing(wsize,color,ax)

% WSTRUCT = SWING(WSIZE,COLR,AX)

if nargin < 3
    ax = gca;
end

wstruct = wing(wsize);
wstruct.handle = patch(...
    'parent'   ,ax,...
    'vertices' ,wstruct.vert,...
    'faces'    ,wstruct.faces,...
    'linewidth',2,...
    'facecolor','none',...
    'edgecolor',color,...
    'visible'  ,'on'); 
