p = [...
    '/home/jsola/SLAM/Slam:', ...
    '/home/jsola/SLAM/Simulation:', ...
    '/home/jsola/SLAM/Points:', ...
    '/home/jsola/SLAM/Observations:', ...
    '/home/jsola/SLAM/Math:', ...
    '/home/jsola/SLAM/Lines:', ...
    '/home/jsola/SLAM/Kinematics:', ...
    '/home/jsola/SLAM/InterfaceLevel:', ...
    '/home/jsola/SLAM/HighLevel:', ...
    '/home/jsola/SLAM/Graphics:', ...
    '/home/jsola/SLAM/FrameTransforms/rotations:', ...
    '/home/jsola/SLAM/FrameTransforms:', ...
    '/home/jsola/SLAM/EKF:', ...
    '/home/jsola/SLAM/DetectionMatching:', ...
    '/home/jsola/SLAM/DataManagement:', ...
    ];

path(p,path);

clear p

cd ~/SLAM/
