format compact

slam_dir = pwd;

p = [...
    [ slam_dir '/Slam:'], ...
    [ slam_dir '/Simulation:'], ...
    [ slam_dir '/Points:'], ...
    [ slam_dir '/Observations:'], ...
    [ slam_dir '/Math:'], ...
    [ slam_dir '/Lines:'], ...
    [ slam_dir '/Kinematics:'], ...
    [ slam_dir '/InterfaceLevel:'], ...
    [ slam_dir '/HighLevel:'], ...
    [ slam_dir '/Graphics:'], ...
    [ slam_dir '/FrameTransforms/Rotations:'], ...
    [ slam_dir '/FrameTransforms:'], ...
    [ slam_dir '/EKF:'], ...
    [ slam_dir '/DetectionMatching:'], ...
    [ slam_dir '/DataManagement:'], ...
    [ slam_dir ':'], ...
    ];

path(p,path);

clear p

set(0, 'DefaultFigureWindowStyle', 'docked');
