% INITMAPFIG  Initialize map figure objects

renderer = 'opengl';

% Map figure
mapFig = figure(1);
clf;
set(mapFig,...
    'doublebuffer','on',...
    'renderer',renderer,...
    'toolbar','none',...
    'color','w');
%    'position',[1     1   400    250],...
cameratoolbar('show');
cameratoolbar('setmode','orbit');

% Map viewpoint
mapObs       = mapObserver(world,mapView);

% Axes
axis equal
mapAxes = gca;
set(mapAxes,...
    'parent',mapFig,...
    'position',[0 0 1 1],...
    'drawmode','fast',...
    'nextplot','replacechildren',...
    'projection',mapProj,...
	'CameraPosition',mapObs.X,...
	'CameraPositionMode','manual',...
	'CameraUpVector',mapObs.upvec,...
	'CameraUpVectorMode','manual',...
	'CameraViewAngle',mapObs.fov,...
	'CameraViewAngleMode','manual',...
	'CameraTarget',mapObs.tgt,...
	'CameraTargetMode','manual',...
    'xlim',[world.xMin world.xMax],...
    'ylim',[world.yMin world.yMax],...
    'zlim',[world.zMin world.zMax],...
    'xcolor','w',...
    'ycolor','w',...
    'zcolor','w',...
    'color' ,'w');


% Ground
[x,y] = meshgrid(world.xMin:2:world.xMax,world.yMin:2:world.yMax);
z = zeros(size(x));
dispGround = surface(...
    'parent',mapAxes,...
    'XData',x,...
    'YData',y,...
    'ZData',z,...
    'FaceColor','none',...
    'EdgeColor',[.6 .8 .8],...
    'Marker','none');

% Estimated Camera graphics
[te,Re] = getTR(Cam);
n = size(Cam.graphics.vert0,1);
Te = te*ones(1,n);
Cam.graphics.vert = Cam.graphics.vert0*Re'+Te'; 
dispEstCam = patch(...
    'parent'   ,mapAxes,...
    'vertices' ,Cam.graphics.vert,...
    'faces'    ,Cam.graphics.faces,...
    'facecolor','g',...
    'visible'  ,drawCamera); % solid green camera estimate

% Simulated camera graphics
dispSimuCam = patch(...
    'parent'   ,mapAxes,...
    'vertices' ,Cam.graphics.vert,...
    'faces'    ,Cam.graphics.faces,...
    'facecolor','b',...
    'visible'  ,drawCamera); % solid blue simulated camera

% Camera position uncertainty
dispElliCam = line(...
    'parent',mapAxes,...
    'xdata',[],...
    'ydata',[],...
    'zdata',[],...
    'marker','none',...
    'color','r',...
    'linestyle','-',...
    'linewidth',1,...
    'visible','on');

% trajectory
dispTraj = line(...
    'parent',mapAxes,...
    'xdata',[],'ydata',[],'zdata',[],...
    'color','g');

% Landmarks in map figure
initDrawMapLines;

% Ground truth - just in simulation.
dispWorld = drawSegmentsObject(world.segments,'b',3);


