% INITIMAGEFIG  Initialize image plane figure


% figure
imgFig = figure(2);
set(imgFig,...
    'renderer','opengl');
%     'position',[ 1   1   360   270],...
clf

% image grid cells
xticks  = subImage.rights(2:end-1);
yticks  = subImage.botts(2:end-1);
gridVis = 'off';

% axes
axis equal
imgAxes = gca;
set(get(imgAxes,'title'),...
    'string','Camera view');
set(imgAxes,...
    'position',[0 0 1 1],...
    'xtick',xticks,...
    'ytick',yticks,...
    'xgrid',gridVis,...
    'ygrid',gridVis,...
    'gridlinestyle',':',...
    'xlim',[0 Cam.imSize(1)],...
    'xaxislocation','top',...
    'ylim',[0,Cam.imSize(2)],...
    'ydir','reverse',...
    'layer','top',...
    'fontsize',8,...
    'color' ,'k');

% % image
% dispImage=image(...
%     'parent',imgAxes,...
%     'cdata',Image{1},...
%     'alphadata',1);
%
% colormap(gray(256));

% Landmarks in Image figure
initDrawImgLines;

% Ground truth image
[obsSegments,visSegments] = projectSegment(SimuCam,world.segments);
if drawObservations
    dispProjWorld = drawSegmentsImage(obsSegments,'b',3); % image
end
