% INITDRAWPROJOBJS  Initialize graphics for projected objects


for c=1:2
    % points
    for i=1:maxObj
        dispProjObj(c).elli(i) = line(...
            'parent',ax2(c),...
            'xdata',[],...
            'ydata',[],...
            'color','y',...
            'marker','none',...
            'linestyle','-',...
            'linewidth',linewidth);
    end

    dispProjObj(c).center = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','y',...
        'marker','+',...
        'linestyle','none');

    dispProjObj(c).obs = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','y',...
        'linestyle','none',...
        'marker','.');

end
