% INITDRAWLMKS

% points
for i=1:Lmk.maxPnt
    dispPnt.elli(i) = line(...
        'parent',ax21,...
        'xdata',[],...
        'ydata',[],...
        'color','c',...
        'marker','none',...
        'linestyle','-',...
        'linewidth',.5);
end

dispPnt.center = line(...
    'parent',ax21,...
    'xdata',[],...
    'ydata',[],...
    'color','b',...
    'marker','.',...
    'linestyle','none');


% rays
for i=1:Ng*Lmk.maxRay
    dispRay.elli(i) = line(...
        'parent',ax21,...
        'xdata',[],...
        'ydata',[],...
        'color','m',...
        'marker','none',...
        'linestyle','-',...
        'linewidth',.5);
end

dispRay.center = line(...
    'parent',ax21,...
    'xdata',[],...
    'ydata',[],...
    'color','r',...
    'marker','.',...
    'linestyle','none');

