function Ray = measureRay(Rob,Cam,Ray,ns)

% MEASURERAY Measure point via active search
%   RAY = MEASURERAY(ROB,CAM,RAY,NS) searches the ray RAY inside
%   the NS-sigma set of projected ellipses that are previously
%   computed for camera CAM. It updates the whole RAY structure.

cam = Cam.id;

% i. Search patch
Ray.wPatch = patchResize(...
   Ray.sig,...
   Ray.Prj(cam).sr^-1);

patchSize = size(Ray.sig.I,1);
Ray.Prj(cam).region = ray2par(...
   Ray,...
   cam,...
   ns,...
   patchSize); % region to scan

[ Ray.Prj(cam).y,...
   Ray.Prj(cam).sc,...
   Ray.Prj(cam).cPatch] = patchScan(...
   cam,...
   Ray.wPatch,...
   Ray.Prj(cam).region,...
   Ray.Prj(cam).region.x0,...
   .98,...
   .89);
