function [Pnt,Obs] = measurePnt(Rob,Cam,Pnt,ns,reproject,Obs)

% MEASUREPNT Measure point via active search
%   PNT = MEASUREPNT(ROB,CAM,PNT,NS) searches the point PNT
%   inside the NS-sigma projected ellipses that are previously
%   computed for camera CAM. It updates the whole PNT structure.
%
%   PNT = MEASUREPNT(...,REPROJ,OBS) with REPROJ = true
%   additionally reprojects the point onto the image plane with
%   observation OBS

cam = Cam.id;

% re-project point to get actual linearizations
if (nargin >= 4) & reproject
   Pnt = projectPnt(...
      Rob,...
      Cam,...
      Pnt,...
      Obs.R);
end

% i. Search patch
patchSize = size(Pnt.sig.I,1);
Pnt.Prj(cam).region = pnt2par(...
   Pnt,...
   ns,...
   cam,...
   patchSize); %  region to scan

Pnt.wPatch = patchResize(...
   Pnt.sig,...
   Pnt.Prj(cam).sr^-1); % warp patch

[ Pnt.Prj(cam).y,...
   Pnt.Prj(cam).sc,...
   Pnt.Prj(cam).cPatch] ...
   ...
   = patchScan(...
   ...
   cam,...
   Pnt.wPatch,...
   Pnt.Prj(cam).region,...
   Pnt.Prj(cam).region.x0,...
   .98,...
   .89);

Obs.y = Pnt.Prj(cam).y;
