% INITIMAGE Initialize global Image variable

Image{1} = oneShot([imgdir imgname{1}],fmin-1,equalizeIm);
Image{2} = oneShot([imgdir imgname{2}],fmin-1,equalizeIm);

% Initialize image regions for landmark detections
subImage = uniformRegions(...
    Cam(1).imSize(2),Cam(1).imSize(1),...
    regions,regions,...
    1,1,...
    ones(1,(regions-2)^2));
