% INITDRAWIMGLINES  Initialize graphic objects for lines in the image.
%
%   Use DISPIMGLINES to display them.
%
%   See also DISPIMGLINES.

linewidth = 1;

for c = 1:numel(Cam)

    % lines
    for i=1:Lmk.maxLine
        obsTab(c,i).dispImg.mean = line(...
            'parent',imgAxes(c),...
            'xdata',[],...
            'ydata',[],...
            'color',[0 .35 0],...
            'marker','none',...
            'linestyle','-',...
            'linewidth',linewidth);

        obsTab(c,i).dispImg.cov1 = line(...
            'parent',imgAxes(c),...
            'xdata',[],...
            'ydata',[],...
            'color','y',...
            'marker','none',...
            'linestyle','-');

        obsTab(c,i).dispImg.cov2 = line(...
            'parent',imgAxes(c),...
            'xdata',[],...
            'ydata',[],...
            'color','y',...
            'marker','none',...
            'linestyle','-');

        obsTab(c,i).dispImg.txt = text(...
            'parent',imgAxes(c),...
            'position',[5 5],...
            'color','g',...
            'string','',...
            'horizontalalignment','center',...
            'verticalalignment','middle');
    end

end

