% INITOBSTAB  Init observations table.
%   INITOBSTAB is a script for initializing the obserbations table. Use
%   this file to add new fields to the observation table. 
%
%   The observations table, obsTab, is a global variable, a 2-dimmensional
%   array, containing a bunch of information about landmarks observations
%   performed from a variety of sensors. It is indexed by the sensor ID and
%   by the landmark ID. Examples of stored information are (not limited
%   to):
%
%       .rawy    the observation as given by the fearure matcher
%       .rawR    the cov. mat. of rawy
%       .y       the observation in innovation space
%       .R       the cov. mat. of y.
%       .u       the expectation in innovation space
%       .U       the expectation cov mat
%       .dU      the determinant of U
%       .z       the innovation
%       .Z       the cov mat of Z
%       .Hc      the Jacobian wrt the camera pose
%       .Hk      the Jac. wrt the sensor intrinsic params
%       .Hl      the jac. wrt the landmark position
%       .vis     flag for visible lmk
%       .matched flag for matched lmk
%       .updated flag for updated lmk
%
%   among others. Only information relating the pair sensor-landmark should
%   go here. Information about the landmark itself should be stored in the
%   landmark's own structure.

global obsTab

obsTab = struct(...
    'rawy',    [],...
    'rawR',    [],...
    'y',       [],...
    'R',       [],...
    'hm',      [],...
    'HM',      [],...
    'u',       [],...
    'U',       [],...
    'dU',      [],...
    'z',       [],...
    'Z',       [],...
    'iZ',      [],...
    'MD',      [],...
    'Hc',      [],...
    'Hk',      [],...
    'Hl',      [],...
    'vis',     false,...
    'matched', false,...
    'updated', false);

% Extend to both sensor and landmarks dimensions
obsTab(numel(Cam),Lmk.maxLine).y = [];
[obsTab.vis] = deal(false);
[obsTab.matched] = deal(false);
[obsTab.updated] = deal(false);
