% INITCRAWMAPLINES  Initialize graphic objects for drawing lines in the map
%
%   Use DRAWMAPLINES to draw them.
%
%   See also DRAWMAPLINES.

% lines
for i=1:Lmk.maxLine
    dispMapLines(i).seg = line(...
        'parent',mapAxes,...
        'xdata',[],...
        'ydata',[],...
        'color','g',...
        'marker','none',...
        'linestyle','-',...
        'linewidth',2);
    dispMapLines(i).cov1 = line(...
        'parent',mapAxes,...
        'xdata',[],...
        'ydata',[],...
        'color',[1 .7 .7],...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1);
    dispMapLines(i).cov2 = line(...
        'parent',mapAxes,...
        'xdata',[],...
        'ydata',[],...
        'color',[1 .7 .7],...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1);
    dispMapLines(i).txt = text(...
        'parent',mapAxes,...
        'position',[5 5 5],...
        'color','k',...
        'string','',...
        'margin',5,...
        'horizontalalignment','center',...
        'verticalalignment','middle');
end
