% INITMAPFIG  Initialize visualization

robotSize  = 3;

% renderer = 'painters';
% renderer = 'zbuffer';
renderer = 'opengl';

bgndcolor = 'w';


% FIGURE 1
fig1 = figure(1);
clf;
set(fig1,...
    'doublebuffer','on',...
    'renderer',renderer,...
    'toolbar','none',...
    'color',bgndcolor);
%     'position',[1     1   400    250],...
cameratoolbar('show');
cameratoolbar('setmode','orbit');

% Axes
xmin = 100-25;
xmax = 100+55;
ymin = 100-20;
ymax = 100+20;
zmin = 100-20;
zmax = 100+20;
initObserver;
axis equal
ax1 = gca;
set(ax1,...
    'parent',fig1,...
    'position',[0 0 1 1],...
    'drawmode','fast',...
    'nextplot','replacechildren',...
    'projection',mapProj,...
	'CameraPosition',obsCam.X(1:WDIM),...
	'CameraPositionMode','manual',...
	'CameraTarget',obsTgt.X(1:WDIM),...
	'CameraTargetMode','manual',...
	'CameraUpVector',obsCam.upvec,...
	'CameraUpVectorMode','manual',...
	'CameraViewAngle',obsCam.a,...
	'CameraViewAngleMode','manual',...
    'xlim',[xmin xmax],...
    'ylim',[ymin ymax],...
    'zlim',[zmin zmax],...
    'xcolor',bgndcolor,...
    'ycolor',bgndcolor,...
    'zcolor',bgndcolor,...
    'color',bgndcolor);


% Ground
[x,y] = meshgrid(xmin:5:xmax,ymin:5:ymax);
z = 100+zeros(size(x));
sh = surface(...
    'parent',ax1,...
    'XData',x,...
    'YData',y,...
    'ZData',z,...
    'FaceColor','none',...
    'EdgeColor',[.6 .8 .8],...
    'Marker','none');

% True world
dispWorld = line(...
    'parent',ax1,...
    'xdata',World(1,:),...
    'ydata',World(2,:),...
    'zdata',World(3,:),...
    'linestyle','none',...
    'marker','+',...
    'color','r');


% Estimated robot
Rob.graphics = thickVehicle(robotSize);
[te,Re] = getTR(Rob);
Te = te*ones(1,6);
Rob.graphics.vert = Rob.graphics.vert0*Re'+Te'; 
dispEstRob = patch(...
    'parent'   ,ax1,...
    'vertices' ,Rob.graphics.vert,...
    'faces'    ,Rob.graphics.faces,...
    'facecolor','b',...
    'visible'  ,'on'); % solid blue robot estimate

% Camera in estimated robot
camBase      = [0;0;0];
camSensor    = Cam.X(1:WDIM);
camPletine   = [camBase(1:2);camSensor(3)];
Cam.graphics = fromFrame(Rob,[camBase camPletine camSensor]);
dispEstCam   = line(...
    'parent'   	     ,ax1,...
    'xdata'          ,Cam.graphics(1,:),...
    'ydata'          ,Cam.graphics(2,:),...
    'zdata'          ,Cam.graphics(3,:),...
    'linestyle'      ,'-',...
    'marker'         ,'.',...
    'color'          ,'m',...
    'visible'        ,'on'     ); % camera optical center

% Robot uncertainty
dispEstElli = line(...
    'parent',ax1,...
    'xdata',[],...
    'ydata',[],...
    'zdata',[],...
    'color','m',...
    'marker','none');
    

% Map usage plot
if plotUsed
ax2 = axes(...
    'parent',fig1,...
    'position',[.07 .01 .45 .06],...
    'fontsize',7,...
    'fontweight','normal',...
    'xaxislocation','top',...
    'xcolor',[.4 .7 .4],...
    'ycolor',[.7 .4 .4],...
    'ticklength',[0 .02],...
    'ytick',[0.2 0.9],...
    'yticklabel',['FREE';'USED'],...
    'ylim',[0 1.1]);
    
    % usage in blue
    usedLm = line(...
        'parent',ax2,...
        'color','b',...
        'linewidth',1,...
        'xdata',1:Map.N,...
        'ydata',zeros(1,Map.N));
    
    % max used in red
    maxLm = line(...
        'parent',ax2,...
        'color','r',...
        'linewidth',3,...
        'xdata',[0 0],...
        'ydata',[0 1]);
    
    % set to main figure for camera control
    set(fig1,'currentaxes',ax1);
    
end

% Landmarks in map figure
initDrawMapLmks;

