% INITDRAWMAPLMKS  Initialize graphics for map landmarks


% points
for i=1:Lmk.maxPnt
    dispMapPnt.elli(i) = line(...
        'parent',ax1,...
        'xdata',[],...
        'ydata',[],...
        'color',[.7 .7 1],...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1);
end

dispMapPnt.center = line(...
    'parent',ax1,...
    'xdata',[],...
    'ydata',[],...
    'color','b',...
    'marker','.',...
    'linestyle','none');


