% INITDRAWPROJLMKS  Initialize graphics for projected landmarks

% points
for i=1:Lmk.maxPnt
    dispProjPnt.elli(i) = line(...
        'parent',ax21,...
        'xdata',[],...
        'ydata',[],...
        'color','b',...
        'marker','none',...
        'linestyle','-',...
        'linewidth',1+(video~=0));
end

dispProjPnt.center = line(...
    'parent',ax21,...
    'xdata',[],...
    'ydata',[],...
    'color','b',...
    'marker','+',...
    'linestyle','none');

dispObsPnt = line(...
    'parent',ax21,...
    'xdata',[],...
    'ydata',[],...
    'color','c',...
    'linestyle','none',...
    'marker','.');


