% INITIMAGE Initialize global Image variable

Image{1} = oneShot([imgdir imgname],fmin,equalizeIm);

% Initialize image regions for landmark detections
if regions
    cm = 1; rm = 1;
    subImage = uniformRegions(...
        Cam.imSize(2),Cam.imSize(1),...
        regions,regions,...
        rm,cm,...
        ones(1,(regions-2*rm)*(regions-2*cm)));
else
    subImage = uniformRegions(Cam.imSize(2),Cam.imSize(1),7,7,1,1,...
        [1 1 1 1 1,...
        +1 1 1 1 1,...
        +1 1 1 1 1,...
        +0 1 0 1 0,...
        +0 0 1 0 0]);
end
