% INITIMAGEFIG  Initialize image plane figure


% figure
fig2 = figure(2);
set(fig2,...
    'position',[ 1   331   410   340],...
    'renderer','opengl');
clf

% image regions
u0      = subImage.u0;
du      = subImage.size;
nreg    = size(u0,2);
nrows   = subImage.nrows;
ncols   = subImage.ncols;
xidx    = 1:ncols;
yidx    = 1:ncols:nreg;
xticks  = [u0(1,xidx) u0(1,end)+du(1,end)];
yticks  = [u0(2,yidx) u0(2,end)+du(2,end)];
gridVis = 'off';

% axes
axis equal
ax21 = gca;
set(get(ax21,'title'),...
    'string','Robot''s camera view');
set(ax21,...
    'position',[.05 .05 .9 .9],...
    'xtick',xticks,...
    'ytick',yticks,...
    'xgrid',gridVis,...
    'ygrid',gridVis,...
    'gridlinestyle',':',...
    'xlim',[0 Cam.imSize(1)],...
    'xaxislocation','top',...
    'ylim',[0,Cam.imSize(2)],...
    'ydir','reverse',...
    'layer','top',...
    'fontsize',8);

% image
dispImage=image(...
    'parent',ax21,...
    'cdata',Image{1},...
    'alphadata',1);

colormap(gray(256));

% Landmarks in Image figure
initDrawProjLmks;

