function dispPatches(dispPatch)

global Lmk

blankPatch = zeros(15);

% Idps
visIdpsIdx = find([Lmk.Idp.vis0] & [Lmk.Idp.used]);

ni = numel(visIdpsIdx);

for i = 1:min(ni,15)
        idx = visIdpsIdx(i);
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-4),...
            Lmk.Idp(idx).sig.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-3),...
            Lmk.Idp(idx).Prj(1).wPatch.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-2),...
            Lmk.Idp(idx).Prj(1).cPatch.I,...
            ['sc=' num2str(100*Lmk.Idp(idx).Prj(1).sc,'%.1f')]);
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-1),...
            Lmk.Idp(idx).Prj(2).wPatch.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-0),...
            Lmk.Idp(idx).Prj(2).cPatch.I,...
            ['sc=' num2str(100*Lmk.Idp(idx).Prj(2).sc,'%.1f')]);
        
end

for i = ni+1 : 15
        set(dispPatch(5*i-4),'cdata',blankPatch);
        set(dispPatch(5*i-3),'cdata',blankPatch);
        set(dispPatch(5*i-2),'cdata',blankPatch);
        set(dispPatch(5*i-1),'cdata',blankPatch);
        set(dispPatch(5*i-0),'cdata',blankPatch);
end

% Pnts
visPntsIdx = find([Lmk.Pnt.vis0] & [Lmk.Pnt.used]);

np = numel(visPntsIdx);

for i = 16 : 15 + min(np,15)
        idx = visPntsIdx(i-15);
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-4),...
            Lmk.Pnt(idx).sig.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-3),...
            Lmk.Pnt(idx).Prj(1).wPatch.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-2),...
            Lmk.Pnt(idx).Prj(1).cPatch.I,...
            ['sc=' num2str(100*Lmk.Pnt(idx).Prj(1).sc,'%.1f')]);
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-1),...
            Lmk.Pnt(idx).Prj(2).wPatch.I,...
            '--');
        
        dispPatch = dispOnePatch(...
            dispPatch,...
            (5*i-0),...
            Lmk.Pnt(idx).Prj(2).cPatch.I,...
            ['sc=' num2str(100*Lmk.Pnt(idx).Prj(2).sc,'%.1f')]);
end

for i = 15 + np+1 : 30
        set(dispPatch(5*i-4),'cdata',blankPatch);
        set(dispPatch(5*i-3),'cdata',blankPatch);
        set(dispPatch(5*i-2),'cdata',blankPatch);
        set(dispPatch(5*i-1),'cdata',blankPatch);
        set(dispPatch(5*i-0),'cdata',blankPatch);
end


return


% local functions

function dispPatch = dispOnePatch(dispPatch,ptchId,ptch,txt)

set(dispPatch(ptchId),'cdata',ptch);
axc = get(dispPatch(ptchId),'parent');
tit = get(axc,'title');
set(tit,'string',txt);

return


