
c = camGraphics(0.1);

c.vert = fromFrame(Rob(1),fromFrame(Cam(1),c.vert0'))';

p.vert = robCamPhoto(Rob(2),Cam(2),c.vert');

x = p.vert(1,:);
y = p.vert(2,:);

X = x(c.faces)';
Y = y(c.faces)';

dispProjCam = patch(...
    zeros(size(X)),...
    zeros(size(Y)),...
    'g',...
    'parent',ax2(2),...
    'edgecolor','k',...
    'facecolor','r',...
    'facealpha',0.3,...
    'linewidth',1,...
    'userdata',c);

    
