% INITIMAGEFIG  Initialize image plane figure


% figure
if ~ishandle(2)
    fig2 = figure(2);
    set(fig2,'position',[1 289 1024 384]);
else
    fig2 = figure(2);    
end
set(fig2,'renderer','opengl');
clf

% image regions
u0      = subImage.u0;
du      = subImage.size;
nreg    = size(u0,2);
nrows   = subImage.nrows;
ncols   = subImage.ncols;
xidx    = 1:ncols;
yidx    = 1:ncols:nreg;
xticks  = [u0(1,xidx) u0(1,end)+du(1,end)];
yticks  = [u0(2,yidx) u0(2,end)+du(2,end)];
gridVis = 'on';
gridColor = [.3 .3 .8];

% axes
ax2(1) = axes('parent',fig2);
axis equal
set(get(ax2(1),'title'),...
    'string','Master camera view');
set(ax2(1),...
    'position',[0 0 .5 1],...
    'xtick',xticks,...
    'ytick',yticks,...
    'xgrid','on',...
    'ygrid','on',...
    'gridlinestyle','-',...
    'xcolor',gridColor,...
    'ycolor',gridColor,...
    'xlim',[0 Cam(1).imSize(1)],...
    'xaxislocation','top',...
    'ylim',[0,Cam(1).imSize(2)],...
    'ydir','reverse',...
    'layer','top',...
    'fontsize',8);

ax2(2) = axes('parent',fig2);
axis equal
set(get(ax2(2),'title'),...
    'string','Slave camera view');
set(ax2(2),...
    'position',[.5 0 .5 1],...
    'xtick',xticks,...
    'ytick',yticks,...
    'xgrid','off',...
    'ygrid','off',...
    'gridlinestyle',':',...
    'xlim',[0 Cam(2).imSize(1)],...
    'xaxislocation','top',...
    'ylim',[0,Cam(2).imSize(2)],...
    'ydir','reverse',...
    'layer','top',...
    'fontsize',8);

% image
for c = 1:2
    dispImage(c)=image(...
        'parent',ax2(c),...
        'cdata',Image{c},...
        'alphadata',1);
end

colormap(gray(256));

% Landmarks in Image figure
initDrawProjLmks;


if plotVray
    initDrawVray;
end

% master camera in slave image
initDispPrjCam;
