% INITDRAWEINF  Initialize eInf graphics

eInfHdle.elli = line;
set(eInfHdle.elli,...
    'parent',ax2(2),...
    'color','g',...
    'linewidth',linewidth);

eInfHdle.obs  = line;
set(eInfHdle.obs,...
    'parent',ax2(2),...
    'color','g',...
    'marker','.',...
    'linestyle','none');

