% INITDRAWPROJLMKS  Initialize graphics for projected landmarks

linewidth = 2;

for c=1:2
    % points
    for i=1:Lmk.maxPnt
        dispProjPnt(c).elli(i) = line(...
            'parent',ax2(c),...
            'xdata',[],...
            'ydata',[],...
            'color','b',...
            'marker','none',...
            'linestyle','-',...
            'linewidth',linewidth);
        
        dispProjPnt(c).txt(i) = text(...
            'parent',ax2(c),...
            'position',[5 5],...
            'color','y',...
            'string','',...
            'horizontalalignment','center',...
            'verticalalignment','middle');
    end

    dispProjPnt(c).center = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','b',...
        'marker','+',...
        'linestyle','none');

    dispProjPnt(c).obs = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','c',...
        'linestyle','none',...
        'marker','.');



    % rays
    for i=1:Lmk.maxIdp
        dispProjIdp(c).elli(i) = line(...
            'parent',ax2(c),...
            'xdata',[],...
            'ydata',[],...
            'color','m',...
            'marker','none',...
            'linestyle','-',...
            'linewidth',linewidth);
        
        dispProjIdp(c).txt(i) = text(...
            'parent',ax2(c),...
            'position',[1 1],...
            'color','y',...
            'string','',...
            'horizontalalignment','center',...
            'verticalalignment','middle');
    end

    dispProjIdp(c).center = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','m',...
        'marker','+',...
        'linestyle','none');

    dispProjIdp(c).obs = line(...
        'parent',ax2(c),...
        'xdata',[],...
        'ydata',[],...
        'color','r',...
        'linestyle','none',...
        'marker','.');

end
