function drawHmgLmk(MapFig, Lmk, color)

% DRAWEUCLMK  Draw Euclidean point landmark in MapFig.

global Map

posOffset = [0;0;.2];
ran=Lmk.state.r;

% Positioning euclidian
hmg = Map.x(ran) ;
HMG = Map.P(ran,ran) ;

% Covariance
[eucl, EUCLhmg] = hmg2p(hmg) ;
EUCL = EUCLhmg*HMG*EUCLhmg' ;

% the ellipse
[X,Y,Z] = cov3elli(eucl, EUCL, 3, 10) ;
set(MapFig.estLmk(Lmk.lmk).ellipse,...
    'xdata',   X,...
    'ydata',   Y,...
    'zdata',   Z,...
    'color',   color,...
    'visible', 'on');

% the measurement:
y = eucl;
set(MapFig.estLmk(Lmk.lmk).mean,...
    'xdata',   y(1),...
    'ydata',   y(2),...
    'zdata',   y(3),...
    'color',   satColor(color),...
    'visible', 'on');

% the label
pos = eucl + posOffset;
set(MapFig.estLmk(Lmk.lmk).label,...
    'position', pos,...
    'string',   num2str(Lmk.id),...
    'visible',  'on');
